// React/demo/src/copmponents/Nav.jsx
import React from 'react'
import { Link } from 'react-router-dom'
 
const Nav = () => {
  return (
    <nav className="navbar navbar-expand-lg bg-body-tertiary">
  <div className="container-fluid">
    <Link className="navbar-brand" to="/">Pro</Link>
    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span className="navbar-toggler-icon"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarNav">
      <ul className="navbar-nav">
        <li className="nav-item">
          <Link className="nav-link active" aria-current="page" to="/">Home</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/about">About Us</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/products">Products</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/contacts">Contact Us</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/post">Post</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/user">User</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/gallery">Gallery</Link>
        </li>
      </ul>
    </div>
  </div>
</nav>
  )
}
 
export default Nav

// Angularcrud/crud/src/app/components/nav/nav.component.ts
import { Component,OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ProductsService } from '../../product/products.service';
 
@Component({
  selector: 'app-nav',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './nav.component.html',
  styleUrl: './nav.component.css'
})
export class NavComponent implements OnInit {
  count:number=0;
  constructor(private proser:ProductsService){}
  ngOnInit(): void {
    this.proser.$subject.subscribe((data:any)=>{
       this.count=data.length;
    })
  }
 
}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active"  routerLink="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/addproduct">AddProduct</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" routerLink="/addproduct">Cart
              @if(count>0){
                ({{count}})
              }
            </a>
          </li>
    
        </ul>
      </div>
    </div>
  </nav>
