// Angular/demo/src/app/nav/nav.component.ts

import { Component } from '@angular/core';
import { RouterLink } from '@angular/router'
import { HomeComponent } from '../home/home.component';
@Component({
  selector: 'app-nav',
  imports: [RouterLink,HomeComponent],
  templateUrl: './nav.component.html',
  styleUrl: './nav.component.css'
})
export class NavComponent {
 
}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active"> <a routerLink="/" class="nav-link">Home</a></li>
        <li class="nav-item"> <a routerLink="/about" class="nav-link">About Us</a></li>
        <li class="nav-item "> <a routerLink="/gallery" class="nav-link">Gallery</a></li>
        <li class="nav-item "> <a routerLink="/contact"class="nav-link">Contact Us</a></li>
        
    </ul>
</div>
</nav>

// ReactProject/myProject/src/components/Nav.jsx
import React from 'react'
import { Link } from 'react-router-dom'
const Nav = () => {
    return (
        <div>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container-fluid">
                    <Link class="navbar-brand" to="/">ITC Bootcamp</Link>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="/">Home</Link>
                            </li>
                            <li class="nav-item">
                                <Link class="nav-link" href="Banner">Banner</Link>
                            </li>
                            <li>
                                <Link class="nav-link " href='Gallery'>Gallery</Link>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link " href='Footer'>Footer</Link>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    )
}

export default Nav
