// React/demo/src/copmponents/Post.jsx
import React, { useEffect, useState } from 'react';
import axios from 'axios';
const Posts = () => {
    const [postData,setPostData]=useState([]);
    useEffect(()=>{
      const URL="https://jsonplaceholder.typicode.com/posts";
      axios.get(URL)
      .then(res=> {
        console.log(res.data)
        setPostData(res.data)
    })
      .catch(err=> console.log(err))
    },[])
  return (
    <div>
        <h2> Latest Posts</h2>
        <section>
             {postData.map(post=>
                <div key={post.id}>
                   <h4> {post.title} </h4>
                   <p> {post.body} </p>
                   <hr/>
                </div>
             )}
        </section>
    </div>
  )
}
 
export default Posts

// NewAngular/pro/src/app/components/post/post.component.ts
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
 
@Component({
  selector: 'app-post',
  standalone: true,
  imports: [],
  templateUrl: './post.component.html',
  styleUrl: './post.component.css'
})
export class PostComponent {
  postData:any;
  constructor(private http:HttpClient){}
  fetchPosts(){
    const URL="https://jsonplaceholder.typicode.com/posts";
    this.http.get(URL)
    .subscribe({
       next:(data:any)=>{
          console.log(data);
          this.postData=data;
       },
       error:(err)=>{
         console.log(err)
       }
    })
  }
}
<h2> Jsonplaceholder Posts</h2>
<button (click)="fetchPosts()"> Fetch Posts</button>
<div>
    @for(post of postData;track post.id){
        <div>
            <h4> {{post.title}}</h4>
            <p> {{post.body}}</p>
            <hr />
        </div>
    }
</div>
