// React/Crud/src/components/Home.jsx
import React, { useContext, useEffect, useState } from 'react'
import { deleteProduct, getAllProduct } from '../services/ProductService';
import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import ProductList from './ProductList';
import Swal from 'sweetalert2';
//import { CartContext } from '../context/CartContext';
import { useDispatch } from 'react-redux';
import { myaddCart } from '../store/CartSlice';
const Home = () => {
  const [proData, setProData] = useState([]);
  // const {myAddCart}=useContext(CartContext);
  const dispatch = useDispatch();
  useEffect(() => {
    getAllProduct()
      .then(res => {
        console.log(res.data);
        setProData(res.data);
      })
      .catch(err => console.log(err))
  }, [])
  const delPro = (id) => {
    Swal.fire({
      title: "Do you want delete?",
      showDenyButton: true,
      confirmButtonText: "Ok",
      denyButtonText: `Cancel`
    }).then((result) => {
      /* Read more about isConfirmed, isDenied below */
      if (result.isConfirmed) {
        deleteProduct(id)
          .then(res => {
            let data = proData.filter(pro => pro.id != id);
            setProData(data);
            Swal.fire("Product Delete", "", "success");
          })
          .catch(err => console.log(err))

      }
    });
  }
  const addCart = (prod) => {
    if (localStorage.getItem('mycart') != undefined) {
      let flag = 0;
      let arr = JSON.parse(localStorage.getItem('mycart'));
      arr.forEach((val, ind) => {
        if (val.id === prod.id) {
          arr[ind].purchaseQuantity += 1;
          flag = 1;
        }
      })
      if (flag == 0) {
        let cartData = { ...prod, purchaseQuantity: 1 };
        arr.push(cartData)
        // myAddCart(arr);
        dispatch(myaddCart(arr));
        localStorage.setItem('mycart', JSON.stringify(arr));
        alert("Product add cart successfully!");
      }
      else {
        localStorage.setItem('mycart', JSON.stringify(arr));
        // myAddCart(arr);
        dispatch(myaddCart(arr));
        alert("Product add cart successfully!");
      }
    }
    else {
      let arr = [];
      let cartData = { ...prod, purchaseQuantity: 1 };
      arr.push(cartData)
      //  myAddCart(arr);
      dispatch(myaddCart(arr));
      localStorage.setItem('mycart', JSON.stringify(arr));
      alert("Product add cart successfully!");
    }
  }
  return (
    <div>
      <h2> Latest Products</h2>
      <Container>
        <Row>
          {proData.map(product =>
            <Col xs={4} key={product.id}>
              <ProductList prod={product} delPro={delPro} addCart={addCart} />
            </Col>
          )}
        </Row>
      </Container>
    </div>
  )
}

export default Home

// Angularcrud/crud/src/app/components/home/home.component.ts
import { Component,OnInit } from '@angular/core';
import { ProductsService } from '../../product/products.service';
import { Product } from '../../product/product';
import Swal from 'sweetalert2'
import { RouterLink } from '@angular/router';
@Component({
  selector: 'app-home',
  standalone: true,
  imports: [RouterLink],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent implements OnInit {
  productData:Product[]=[];
  constructor(private proser:ProductsService){}
  ngOnInit(): void {
     this.proser.getAllProducts()
     .subscribe({
        next:(data:any)=>{
           console.log(data);
           this.productData=data;
        },
        error:(err)=>{
          console.log(err)
        }
     })
  }
  delPro(id:any){
  //  if(confirm("Do u want to delete?")){
  //     this.proser.deleteProduct(id)
  //     .subscribe({
  //        next:(data:any)=>{
  //          this.productData=this.productData.filter((pro:any)=> pro.id!=id);
  //          Swal.fire("Product Deleted!");
  //        },
  //        error:(err)=>{
  //          console.log(err)
  //        }
  //     })
  //  }
  Swal.fire({
    title: "Do you want to delete?",
    showDenyButton: true,
    // showCancelButton: true,
    confirmButtonText: "Ok",
    denyButtonText: `Cancel`
  }).then((result) => {
    /* Read more about isConfirmed, isDenied below */
    if (result.isConfirmed) {
           this.proser.deleteProduct(id)
      .subscribe({
         next:(data:any)=>{
           this.productData=this.productData.filter((pro:any)=> pro.id!=id);
           Swal.fire("Product Deleted!");
         },
         error:(err)=>{
           console.log(err)
         }
      })
    }
    // else if (result.isDenied) {
    //   Swal.fire("Changes are not saved", "", "info");
    // }
  });
  }
  addCart(id:any){
     if(localStorage.getItem("mycart")!=undefined){
        let data:any=localStorage.getItem("mycart");
        let arr=JSON.parse(data);
        if(arr.includes(id)){
           Swal.fire("Already in a cart!");
        }
        else{
          arr.push(id);
          localStorage.setItem("mycart",JSON.stringify(arr));
          this.proser.addCartSubject(arr);
          Swal.fire("Add Cart Successfully!");
          //window.location.reload();
        }
     }
     else{
        let arr=[];
        arr.push(id);
        localStorage.setItem("mycart",JSON.stringify(arr));
        this.proser.addCartSubject(arr);
        Swal.fire("Add Cart Successfully!");
        //window.location.reload();
     }
  }
}
 
 
<section class="container my-2 mr-auto">
    <h1>Products</h1>
    <div class="row">
            @for (product of productData; track product.id) {
            <div class="col-md-4">
                <div class="card mb-3 bg-dark border-dark p-1" style="width: 18rem;">
                    <div class="card-body bg-light">
                      <h5 class="card-title mx-2">{{product.name}}</h5>
                      <p class="card-text mx-2">Price:{{product.price}}</p>
                      <a [routerLink]="['editpro',product.id]" class="btn btn-primary">Edit</a>
                      <button class="btn btn-danger" (click)="delPro(product.id)"> Delete</button>
                      <button class="btn btn-secondary" (click)="addCart(product.id)"> Add Cart</button>
                    </div>
                  </div>
           </div>
        }
    </div>
       
</section>
