// Angular/demo/src/app/nav/nav.component.ts

import { Component } from '@angular/core';
import { RouterLink } from '@angular/router'
import { HomeComponent } from '../home/home.component';
@Component({
  selector: 'app-nav',
  imports: [RouterLink,HomeComponent],
  templateUrl: './nav.component.html',
  styleUrl: './nav.component.css'
})
export class NavComponent {
 
}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active"> <a routerLink="/" class="nav-link">Home</a></li>
        <li class="nav-item"> <a routerLink="/about" class="nav-link">About Us</a></li>
        <li class="nav-item "> <a routerLink="/gallery" class="nav-link">Gallery</a></li>
        <li class="nav-item "> <a routerLink="/contact"class="nav-link">Contact Us</a></li>
        
    </ul>
</div>
</nav>

// React/demo/src/copmponents/Nav.jsx
import React from 'react'
import { Link } from 'react-router-dom'
 
const Nav = () => {
  return (
    <nav className="navbar navbar-expand-lg bg-body-tertiary">
  <div className="container-fluid">
    <Link className="navbar-brand" to="/">Pro</Link>
    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span className="navbar-toggler-icon"></span>
    </button>
    <div className="collapse navbar-collapse" id="navbarNav">
      <ul className="navbar-nav">
        <li className="nav-item">
          <Link className="nav-link active" aria-current="page" to="/">Home</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/about">About Us</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/products">Products</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/contacts">Contact Us</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/post">Post</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/user">User</Link>
        </li>
        <li className="nav-item">
          <Link className="nav-link" to="/gallery">Gallery</Link>
        </li>
      </ul>
    </div>
  </div>
</nav>
  )
}
 
export default Nav
